version: '3.9'

services:
  frontend:
    # Specify the build context for the frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Map the host port 3000 to the container port 80 (default for Nginx)
    ports:
      - "3000:80"
    # Define dependencies if the frontend needs the backend running
    depends_on:
      - backend
    # Volume for live reloading
    # volumes:
    #   - ./frontend:/app
    networks:
      - app-network

  backend:
    # Specify the build context for the backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Map the host port 5001 to the container port 5001
    ports:
      - "5001:5001"
    # Specify environment variables (example shown)
    environment:
      FLASK_ENV: development
      API_KEY: "your_api_key_here"
    # Volume for live reloading
    # volumes:
    #   - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
