name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./Project/frontend

      - name: Run tests
        run: npm test
        working-directory: ./Project/frontend

      - name: Build React app
        run: npm run build
        working-directory: ./Project/frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./Project/backend

      - name: Run tests
        run: pytest
        working-directory: ./Project/backend

  docker:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build frontend Docker image
        run: |
          docker build -t your-dockerhub-username/frontend:latest ./Project/frontend

      - name: Build backend Docker image
        run: |
          docker build -t your-dockerhub-username/backend:latest ./Project/backend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push your-dockerhub-username/frontend:latest
          docker push your-dockerhub-username/backend:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Add your deployment script/command here
